version: "3.8"

services:
  web:
    build: .
    container_name: mywebsite
    ports:
      - "8080:80"          # Map container port 80 to host port 8080
    volumes:
      - .:/usr/share/nginx/html:ro   # Mount local files as read-only
    restart: unless-stopped

